name: Publish site to gh-pages
on:
  push:
    branches:
      - master 
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4.1.4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Pip install
        run: pip install -r ./scripts/requirements.txt
      - name: Compile speed file 
        run: python ./scripts/length-generator.py
      - name: Compile adversary file 
        run: python ./scripts/adversary-generator.py
      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4.1.4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Pip install
        run: pip install -r ./scripts/requirements.txt
      - name: Compile speed file 
        run: python ./scripts/length-generator.py
      - name: Compile adversary file 
        run: python ./scripts/adversary-generator.py
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
